const cardsData = [
  {
    "id": "zahlbereiche",
    "title": "Zahlbereiche",
    "desc": "Ordne den Zahlbereichen (Natürliche Zahlen, Ganze Zahlen, ...) Zahlen zu.",
    "types": ["quiz"],
    "mobilefriendly": true,
    "link": "zahlbereiche.html",
    "fach": "Mathematik",
    "stufe": [7, 9],
    "wichtig": false,
    "added": "2026-05-26"
  },
  {
    "id": "groessen_umrechnen",
    "title": "Größen umrechnen",
    "desc": "Übe das Umrechnen von Größen in verschiedenen Einheiten.",
    "types": ["learn"],
    "mobilefriendly": true,
    "link": "groessen_umrechnen.html",
    "fach": "Mathematik",
    "stufe": [7,8],
    "wichtig": false,
    "added": "2026-07-25",
    "wip": true
  },
  {
    "id": "waage",
    "title": "Lineare Gleichungen lösen (mit Waagen-Modell)",
    "desc": "Ordne den Zahlbereichen (Natürliche Zahlen, Ganze Zahlen, ...) Zahlen zu.",
    "types": ["uebung"],
    "mobilefriendly": true,
    "link": "waage.html",
    "fach": "Mathematik",
    "stufe": [7,8],
    "wichtig": true,
    "added": "2026-07-25"
  },
  {
    "id": "potenzgesetze",
    "title": "Potenzgesetze",
    "desc": "Übe die Potenzgesetze an verschiedenen Beispielen.",
    "types": ["learn"],
    "mobilefriendly": true,
    "link": "potenzgesetze.html",
    "fach": "Mathematik",
    "stufe": [8,9],
    "wichtig": false,
    "added": "2026-05-25",
    "wip": true
  },
  {
    "id": "potenzen",
    "title": "Quadratzahlen, Potenzen und Wurzeln",
    "desc": "Übe Quadratzahlen, andere Potenzen und Wurzeln",
    "types": ["flash", "quiz"],
    "mobilefriendly": true,
    "link": "potenzen.html",
    "fach": "Mathematik",   // mathematik | informatik | sonstiges (optional)
    "stufe": [8, 9],       // Zahlen oder Strings, [..] für Doppeljahrgänge (optional)
    "wichtig": true,        // rotes "! Wichtig", dauerhaft (optional)
    "added": "2025-09-17",  // "Neu"-Fähnchen im Highlight-Zeitraum (optional)
    "major": "2026-04-14",  // "Update"-Fähnchen im Highlight-Zeitraum (optional)
    "extra": false           // grauer Titel + Stern, über den Schulstoff hinaus (optional)
  },
  {
    "id": "sciNot",
    "title": "Wissenschaftliche Schreibweise",
    "desc": "Übe die wissenschaftliche Schreibweise mit abgetrennter Zehnerpotenz",
    "types": ["quiz"],
    "mobilefriendly": true,
    "link": "wissenschaftliche_schreibweise.html",
    "fach": "Mathematik",
    "stufe": [8, 9],
    "wichtig": false,
    "added": "2026-05-30",
    "extra": false
  },
  {
    "id": "gleichungart",
    "title": "Gleichungsart erkennen",
    "desc": "Welche Gleichungsart liegt vor und wie löst man sie?",
    "types": ["quiz"],
    "mobilefriendly": true,
    "link": "gleichungart.html",
    "fach": "Mathematik",
    "stufe": [10, "Abi"],
    "wichtig": true,
    "added": "2025-10-09",
    // "major": "2026-04-14",
    "extra": false
  },
  {
    "id": "lgs",
    "title": "Lineares Gleichungssystem",
    "desc": "LGS mit 2 oder 3 Gleichungen lösen",
    "types": ["learn"],
    "mobilefriendly": true,
    "link": "lgs.html",
    "fach": "Mathematik",
    "stufe": [8],
    "wichtig": true,
    "added": "2025-09-03",
    "major": "2026-07-25",
    "extra": false
  },
  {
    "id": "scheitelpunktform",
    "title": "Scheitelpunktform",
    "desc": "Umwandeln der Scheitelpunktform üben",
    "types": ["learn"],
    "mobilefriendly": true,
    "link": "scheitelpunktform.html",
    "fach": "Mathematik",
    "stufe": [9],
    "wichtig": false,
    "added": "2025-12-15",
    // "major": "2026-04-14",
    "extra": false
  },
  {
    "id": "geo-scheitelpunkt",
    "title": "GeoGebra: Quadratische Funktionen ablesen/einzeichnen",
    "desc": "Ablesen und Einzeichnen in Scheitelpunktform",
    "types": ["geo"],
    "mobilefriendly": false,
    "link": "https://t1p.de/geogebraScheitelpunkt",
    "fach": "Mathematik",
    "stufe": [9],
    "wichtig": true
  },
  {
    "id": "pq",
    "title": "pq-Formel",
    "desc": "Anwendung der p-q-Formel trainieren",
    "types": ["learn"],
    "mobilefriendly": true,
    "link": "pq.html",
    "fach": "Mathematik",
    "stufe": [9],
    "wichtig": true,
    "added": "2025-09-03",
    // "major": "2026-04-14",
    "extra": false
  },
  {
    "id": "geo-potparam",
    "title": "GeoGebra: Potenzfunktionen Ablesen/Einzeichnen",
    "desc": "Ablesen/Einzeichnen lineartransformierter Potenzfunktionen",
    "types": ["geo"],
    "mobilefriendly": false,
    "link": "https://t1p.de/potparam",
    "fach": "Mathematik",
    "stufe": [9,10],
    "wichtig": false,
    "extra": false
  },
  {
    "id": "geo-koSymm",
    "title": "GeoGebra: Symmetrie bei Polynomen",
    "desc": "Symmetrie am Graphen oder der Funktionsgleichung erkennen",
    "types": ["geo"],
    "mobilefriendly": false,
    "link": "https://t1p.de/koSymm",
    "fach": "Mathematik",
    "stufe": [10, "Abi"],
    "wichtig": false,
    "extra": false
  },
  {
    "id": "grenzverhalten-poly",
    "title": "Grenzverhalten von Polynomen",
    "desc": "Grenzverhalten von Polynomen und Potenzfunktionen bestimmen",
    "types": ["quiz"],
    "mobilefriendly": true,
    "link": "grenzverhalten-poly.html",
    "fach": "Mathematik",
    "stufe": [10, "Abi"],
    "wichtig": false,
    "added": "2026-03-20",
    // "major": "2026-04-14",
    "extra": false
  },
  {
    "id": "polynom-ableitung",
    "title": "Polynome ableiten",
    "desc": "Ableitungen von Polynomen und Potenzfunktionen",
    "types": ["learn"],
    "mobilefriendly": true,
    "link": "polynom-ableitung.html",
    "fach": "Mathematik",
    "stufe": ["Abi"],
    "wichtig": true,
    "added": "2026-02-23",
    // "major": "2026-04-14",
    "extra": false
  },
  {
    "id": "polynom-reko",
    "title": "Polynome Rekonstruieren",
    "desc": "Finden einer Polynomfunktion mit bestimmten Eigenschaften ('Steckbriefaufgaben')",
    "types": ["learn"],
    "mobilefriendly": true,
    "link": "polynom_rekonstruieren.html",
    "fach": "Mathematik",
    "stufe": ["Abi"],
    "wichtig": false,
    "added": "2026-05-21",
    // "major": "2026-04-14",
    "extra": false
  },
  {
    "id": "ableitungen",
    "title": "Weitere Ableitungen",
    "desc": "Ableitungen weiterer Standardfunktionen festigen",
    "types": ["flash"],
    "mobilefriendly": true,
    "link": "ableitungen.html",
    "fach": "Mathematik",
    "stufe": ["Abi"],
    "wichtig": false,
    "added": "2026-01-15",
    // "major": "2026-04-14",
    "extra": false
  },
  {
    "id": "kettenregel",
    "title": "Kettenregel",
    "desc": "Kettenregel sicher anwenden",
    "types": ["learn"],
    "mobilefriendly": true,
    "link": "kettenregel.html",
    "fach": "Mathematik",
    "stufe": ["Abi"],
    "wichtig": false,
    "added": "2026-01-15",
    // "major": "2026-04-14",
    "extra": false
  },
  {
    "id": "produktregel",
    "title": "Produktregel",
    "desc": "Produktregel sicher anwenden",
    "types": ["learn"],
    "mobilefriendly": true,
    "link": "produktregel.html",
    "fach": "Mathematik",
    "stufe": ["Abi"],
    "wichtig": false,
    "added": "2026-01-20",
    // "major": "2026-04-14",
    "extra": false
  },
  {
    "id": "e-fkt",
    "title": "e-Funktion ableiten &amp; zusammenfassen",
    "desc": "Ableiten der e-Funktion und Terme zusammenfassen",
    "types": ["learn"],
    "mobilefriendly": true,
    "link": "e-fkt.html",
    "fach": "Mathematik",
    "stufe": ["Abi"],
    "wichtig": true,
    "added": "2026-01-22",
    // "major": "2026-04-14",
    "extra": false
  },
  {
    "id": "grenzverhalten-e",
    "title": "Grenzverhalten der e-Funktion",
    "desc": "Grenzverhalten der e-Funktion bestimmen",
    "types": ["quiz"],
    "mobilefriendly": true,
    "link": "grenzverhalten-e.html",
    "fach": "Mathematik",
    "stufe": ["Abi"],
    "wichtig": false,
    "added": "2026-01-23",
    "major": "2026-03-20",
    "extra": false
  },
  {
    "id": "integral",
    "title": "Stammfunktionen von Polynomen",
    "desc": "Stammfunktionen von Polynomen finden",
    "types": ["learn"],
    "mobilefriendly": true,
    "link": "integral_uebung.html",
    "fach": "Mathematik",
    "stufe": ["Abi"],
    "wichtig": true,
    "added": "2026-02-19",
    // "major": "2026-04-14",
    "extra": false
  },
  {
    "id": "bestimmtes-integral",
    "title": "Bestimmte Integrale von Polynomen",
    "desc": "Bestimmte Integrale berechnen",
    "types": ["learn"],
    "mobilefriendly": true,
    "link": "bestimmtes_integral_uebung.html",
    "fach": "Mathematik",
    "stufe": ["Abi"],
    "wichtig": true,
    "added": "2026-02-26",
    // "major": "2026-04-14",
    "extra": false
  },
  {
    "id": "geo-integral",
    "title": "GeoGebra: Geometr. Interpret. von Integralen",
    "desc": "Visualisierung bestimmter Integrale",
    "types": ["geo"],
    "mobilefriendly": false,
    "link": "https://www.geogebra.org/calculator/ftgpxxzx",
    "fach": "Mathematik",
    "stufe": ["Abi"],
    "wichtig": false,
    "extra": false
  },
  {
    "id": "aufg-flaechen-integrale",
    "title": "Flächeninhalte unter Graphen von Polynomen",
    "desc": "Flächeninhalte unter Graphen von Polynomen mit bestimmten Integralen",
    "types": ["learn"],
    "mobilefriendly": true,
    "link": "flaeche_polynom_uebung.html",
    "fach": "Mathematik",
    "stufe": ["Abi"],
    "wichtig": true,
    "added": "2026-04-27",
    // "major": "2026-04-14",
    "extra": false
  },
  {
    "id": "aufg-schnittflaechen-integrale",
    "title": "Schnittflächen zwischen Polynom-Graphen",
    "desc": "Schnittflächen zwischen Graphen von Polynomen mit bestimmten Integralen üben",
    "types": ["learn"],
    "mobilefriendly": true,
    "link": "schnittflaeche_polynome.html",
    "fach": "Mathematik",
    "stufe": ["Abi"],
    "wichtig": false,
    "added": "2026-05-12",
    // "major": "2026-04-14",
    "extra": false
  },
  {
    "id": "geo-3DKoord",
    "title": "GeoGebra: 3D-Koordinatensystem einzeichnen",
    "desc": "Visualisierung des 3-dimensionalen Koordinatensystems",
    "types": ["geo"],
    "mobilefriendly": false,
    "link": "https://t1p.de/3DKoord",
    "fach": "Mathematik",
    "stufe": [10, "Abi"],
    "wichtig": false,
    "extra": false
  },
  {
    "id": "geo-koBasis",
    "title": "GeoGebra: Basistransformation",
    "desc": "Visualisierung der Basistransformation",
    "types": ["geo"],
    "mobilefriendly": false,
    "link": "https://t1p.de/koBasis",
    "fach": "Mathematik",
    "stufe": ["Abi"],
    "wichtig": false,
    "extra": true
  },
  {
    "id": "kongruenzsatz",
    "title": "Kongruenzsätze erkennen und zeichnen",
    "desc": "Kongruenzsätze sicher erkennen und zeichnen können",
    "types": ["uebung", "quiz"],
    "mobilefriendly": true,
    "link": "kongruenzsatz.html",
    "fach": "Mathematik",
    "stufe": [7, 9],
    "wichtig": false,
    "added": "2026-05-12",
    "extra": false
  },
  {
    "id": "seiten-benennung",
    "title": "Seiten im rechtwinkligen Dreieck benennen",
    "desc": "Quiz: Ankathete, Gegenkathete, Hypotenuse benennen",
    "types": ["quiz"],
    "mobilefriendly": true,
    "link": "seiten_benennung.html?t1=1&t2=1&t3=0&t4=0",
    "fach": "Mathematik",
    "stufe": [8, 9],
    "wichtig": false,
    "added": "2026-03-09",
    // "major": "2026-04-14",
    "extra": false
  },
  {
    "id": "trig-aufstellen",
    "title": "Winkelbeziehungen im rechtwinkligen Dreieck aufstellen und angeben",
    "desc": "Quiz: Winkelbeziehungen (Sinus, Kosinus, Tangens) aufstellen und angeben",
    "types": ["quiz"],
    "mobilefriendly": true,
    "link": "seiten_benennung.html?t1=0&t2=0&t3=1&t4=1",
    "fach": "Mathematik",
    "stufe": [9],
    "wichtig": false,
    "added": "2026-05-25",
    // "major": "2026-05-25",
    "extra": false
  },
  {
    "id": "trigonometrie",
    "title": "Sinus, Kosinus, Tangens &amp; Pythagoras",
    "desc": "Trigonometrie im <b>rechtwinkligen</b> Dreieck: Sinus, Kosinus, Tangens &amp; Pythagoras anwenden",
    "types": ["learn"],
    "mobilefriendly": true,
    "link": "trigonometrie_uebung.html",
    "fach": "Mathematik",
    "stufe": [8, 9],
    "wichtig": true,
    "added": "2026-03-05",
    // "major": "2026-04-14",
    "extra": false
  },
  {
    "id": "sinuskosinussatz",
    "title": "Sinussatz- und Kosinussatz",
    "desc": "Trigonometrie im <b>beliebigen</b> Dreieck: Sinus- und Kosinussatz anwenden",
    "types": ["learn"],
    "mobilefriendly": true,
    "link": "sinuskosinussatz_uebung.html",
    "fach": "Mathematik",
    "stufe": [9],
    "wichtig": true,
    "added": "2026-03-09",
    // "major": "2026-04-14",
    "extra": false
  },
  {
    "id": "geo-sinus-herleitung",
    "title": "GeoGebra: Herleitung Sinusfunktion",
    "desc": "Visualisierung der Herleitung der Sinusfunktion",
    "types": ["geo"],
    "mobilefriendly": false,
    "link": "https://t1p.de/geogebra-herleitung-sinusfunktion",
    "fach": "Mathematik",
    "stufe": [9,10],
    "wichtig": true,
    "extra": false
  },
  {
    "id": "geo-arkussinus",
    "title": "GeoGebra: Herleitung Arkussinus",
    "desc": "Visualisierung der Arkussinus-Funktion und ihrer Herleitung",
    "types": ["geo"],
    "mobilefriendly": false,
    "link": "https://t1p.de/geogebra-arkussinus",
    "fach": "Mathematik",
    "stufe": [10],
    "wichtig": false,
    "extra": true
  },
  {
    "id": "geo-sinus-ablesen",
    "title": "GeoGebra: Allgemeine Sinusfunktion ablesen/einzeichnen",
    "desc": "Parameter der allgemeinen Sinusfunktion üben",
    "types": ["geo"],
    "mobilefriendly": false,
    "link": "https://t1p.de/geogebra-sinus-parameter-ueben",
    "fach": "Mathematik",
    "stufe": [10],
    "wichtig": true,
    "extra": false
  },
  {
    "id": "geo-sinus-veraendern",
    "title": "GeoGebra: Parameter der Sinusfunktion verändern",
    "desc": "Auswirkungen der Lineartransformations-Parameter verstehen",
    "types": ["geo"],
    "mobilefriendly": false,
    "link": "https://t1p.de/geogebra-sinus-parameter-veraendern",
    "fach": "Mathematik",
    "stufe": [10],
    "wichtig": true,
    "extra": false
  },
  {
    "id": "geo-parameter-einheit",
    "title": "GeoGebra: Parameter am Einheitskreis verstehen",
    "desc": "Herleitung der Parameter über Einheitskreis. Auch: Summe zweier Sinus-Funktionen",
    "types": ["geo"],
    "mobilefriendly": false,
    "link": "https://t1p.de/ko-sinparam-einheit",
    "fach": "Mathematik",
    "stufe": [10],
    "wichtig": false,
    "added": "2026-05-30",
    "major": "2026-04-14",
    "extra": false
  },
  {
    "id": "sinus-toene",
    "title": "Sinus-Funktionen als Töne",
    "desc": "Zusammenhang zwischen Tonhöhe und Frequenz-Parameter b.<br>\
    Wieso haben die Noten genau diese Frequenzen und was bewirken Akkorde",
    "types": ["uebung"],
    "mobilefriendly": true,
    "link": "sinus-toene.html",
    "fach": "Mathematik",
    "stufe": [10],
    "wichtig": false,
    "added": "2026-04-27",
    // "major": "2026-04-14",
    "extra": true
  },
  {
    "id": "geo-fourier",
    "title": "GeoGebra: Fourierreihe",
    "desc": "Visualisierung der Fourierreihe",
    "types": ["geo"],
    "mobilefriendly": false,
    "link": "https://t1p.de/geogebra-fourier",
    "fach": "Mathematik",
    "stufe": [10],
    "wichtig": false,
    "extra": true
  },
  {
    "id": "differenz_trifft",
    "title": "Differenz trifft",
    "desc": "Spielerisch Wahrscheinlichkeiten einschätzen",
    "types": ["game"],
    "mobilefriendly": true,
    "link": "differenz_trifft.html",
    "fach": "Mathematik",
    "stufe": [8, 9],
    "wichtig": false,
    "added": "2026-06-02",
    // "major": "2026-04-14",
    "extra": true
  },
  {
    "id": "baumdiagramm_auswahl",
    "title": "Felder im Baumdiagramm zuordnen",
    "desc": "Ordne zu, an welcher Stelle welche Ereignisse im Baumdiagramm eingetragen werden müssen",
    "types": ["quiz"],
    "mobilefriendly": true,
    "link": "baumdiagramm_felder.html",
    "fach": "Mathematik",
    "stufe": [8, "Abi"],
    "wichtig": false,
    "added": "2026-06-02",
    // "major": "2026-04-14",
    "extra": false
  },
  {
    "id": "vierfeldertafel",
    "title": "Vierfeldertafel",
    "desc": "Fülle die Felder der Vierfeldertafel aus, um damit Wahrscheinlichkeiten (auch bedingte) zu berechnen",
    "types": ["quiz"],
    "mobilefriendly": true,
    "link": "vierfeldertafel.html",
    "fach": "Mathematik",
    "stufe": [10, "Abi"],
    "wichtig": true,
    "added": "2026-06-03",
    // "major": "2026-04-14",
    "extra": false
  },
  {
    "id": "ziegenproblem",
    "title": "Ziegenproblem",
    "desc": "Löse das klassische Ziegenproblem zur Veranschaulichung von Wahrscheinlichkeiten",
    "types": ["quiz"],
    "mobilefriendly": true,
    "link": "ziegenproblem.html",
    "fach": "Mathematik",
    // "stufe": [10, "Abi"],
    "wichtig": false,
    "added": "2026-06-06",
    // "major": "2026-04-14",
    "extra": true,
    "wip": true
  },
  {
    "id": "graphen",
    "title": "Graph erkennen",
    "desc": "Welche Standard-Funktion wird dargestellt?",
    "types": ["flash"],
    "mobilefriendly": true,
    "link": "graphen.html",
    "fach": "Mathematik",
    "stufe": [10],
    "wichtig": true,
    "added": "2026-01-15",
    // "major": "2026-04-14",
    "extra": false
  },
  {
    "id": "binary",
    "title": "Binärzahlen",
    "desc": "Umrechnung zwischen Binär- und Dezimalzahlen üben",
    "types": ["uebung"],
    "mobilefriendly": true,
    "link": "binary.html",
    "fach": "Informatik",
    "stufe": [8],
    "wichtig": true,
    "added": "2026-09-13",
    // "major": "2026-04-14",
    "extra": false
  },
  {
    "id": "rsa",
    "title": "RSA",
    "desc": "RSA-Verschlüsselung Schritt für Schritt üben",
    "types": ["uebung"],
    "mobilefriendly": true,
    "link": "rsa_interaktiv.html",
    "fach": "Informatik",
    "stufe": ["Abi"],
    "wichtig": true,
    "added": "2026-03-20",
    // "major": "2026-04-14",
    "extra": false
  },
  {
    "id": "RAM",
    "title": "RAM-Visualisierung",
    "desc": "Visualisierung des Speicherverhaltens in einem Computer",
    "types": ["uebung"],
    "mobilefriendly": true,
    "link": "ram_viewer.html",
    "fach": "Informatik",
    "stufe": [10, "Abi"],
    "wichtig": false,
    "added": "2026-05-05",
    // "major": "2026-04-14",
    "extra": false
  },
  {
    "id": "annoinformatica",
    "title": "Anno Informatica",
    "desc": "Ordne informatische und Computer-geschichtliche Ereignisse am Zeitstrahl",
    "types": ["game"],
    "mobilefriendly": true,
    "link": "anno.html?subject=informatik",
    "fach": "Informatik",
    "wichtig": false,
    "added": "2026-05-18",
    // "major": "2026-04-14",
    "extra": true
  },
  {
    "id": "supervised-learning",
    "title": "Überwachtes Lernen",
    "desc": "Visualisiere die Funktionsweise von k-nearest neighbors (k-NN) zum überwachtem Lernen (supervised learning) an Beispielen",
    "types": ["uebung"],
    "mobilefriendly": true,
    "link": "supervised_learning.html",
    "fach": "Informatik",
    "stufe": ["Abi"],
    "wichtig": false,
    "added": "2026-06-23",
    // "major": "2026-04-14",
    "extra": false
  },
  {
    "id": "unsupervised-learning",
    "title": "Unüberwachtes Lernen",
    "desc": "Visualisiere die Funktionsweise von Algorithmen (LVQ, k-means) zum unüberwachtem Lernen (unsupervised learning) an Beispielen",
    "types": ["uebung"],
    "mobilefriendly": true,
    "link": "unsupervised_learning.html",
    "fach": "Informatik",
    "stufe": ["Abi"],
    "wichtig": false,
    "added": "2026-06-18",
    // "major": "2026-04-14",
    "extra": false
  },
  {
    "id": "buchstaben-trainer",
    "title": "Buchstaben kennenlernen",
    "desc": "Wie heißen die griechischen (hebräischen, kyrillischen) Buchstaben und wie werden sie geschrieben?",
    "types": ["flash", "quiz"],
    "mobilefriendly": true,
    "link": "buchstaben_trainer.html",
    "fach": "Sonstiges",
    // "stufe": [8, 9],
    "wichtig": false,
    "added": "2026-04-01",
    // "major": "2026-04-14",
    "extra": true
  },
  {
    "id": "schrift-trainer",
    "title": "Schrift-Trainer",
    "desc": "Übersetze die Schrift von einzelnen Wörtern in andere Buchstabensysteme",
    "types": ["uebung"],
    "mobilefriendly": true,
    "link": "schrift_trainer.html",
    "fach": "Sonstiges",
    // "stufe": [8, 9],
    "wichtig": false,
    "added": "2026-04-07",
    // "major": "2026-04-14",
    "extra": true
  },
  {
    "id": "trio",
    "title": "TRIO",
    "desc": "Zufallsgeneriertes Spielfeld für das Mathe-Spiel TRIO",
    "types": ["game"],
    "mobilefriendly": true,
    "link": "TRIO.html",
    "fach": "Mathematik",
    // "stufe": [8, 9],
    "wichtig": false,
    "added": "2024-04-01",
    "major": "2026-05-30",
    "extra": true
  },
  {
    "id": "annomathematica",
    "title": "Anno Mathematica",
    "desc": "Ordne mathematische Ereignisse am Zeitstrahl, von der Antike bis zur Gegenwart.",
    "types": ["game"],
    "mobilefriendly": true,
    "link": "anno.html",
    "fach": "Mathematik",
    // "stufe": [8, 9],
    "wichtig": false,
    "added": "2026-04-27",
    "major": "2026-05-04",
    "extra": true
  },
  {
    "id": "studiengaenge",
    "title": "Studienwahl Mathematik",
    "desc": "Orientierungshilfe für Studiengänge rund um Mathematik",
    "types": ["info"],
    "mobilefriendly": true,
    "link": "studiengaenge_mathematik.html",
    "fach": "Mathematik",
    // "stufe": [8, 9],
    "wichtig": false,
    "added": "2026-03-26",
    // "major": "2026-04-14",
    "extra": true
  },
  {
    "id": "geographie",
    "title": "Geographie-Spiel: Finde die Orte",
    "desc": "Finde die Orte auf der Karte, umso genauer du bist, desto mehr Punkte bekommst du.",
    "types": ["spiel"],
    "mobilefriendly": true,
    "link": "./Geographie/geographie.html",
    "fach": "Sonstiges",
    // "stufe": [8, 9],
    "wichtig": false,
    "added": "2026-07-25",
    // "major": "2026-04-14",
    "extra": true
  }
];