// woerter_hebraeisch.js – Hebräisches Wörterbuch für den Schrift-Trainer
// Format: null = algorithmische Transkription korrekt
//         ['HebrForm mit Nikud', 'Romanisierung']
// Musterlösung (Vergleich) = stripNikud(Form), Nikud für Anzeige + fromHe-Transkription
var WOERTER_HEBRAEISCH = {

  // Feiertage
  'Schabbat':            ['שַׁבָּת',           'Schabbat'],
  'Pessach':             ['פֶּסַח',            'Pessach'],
  'Chanukka':            ['חֲנֻכָּה',          'Chanukka'],
  'Sukkot':              ['סֻכּוֹת',           'Sukkot'],
  'Purim':               ['פּוּרִים',          'Purim'],
  'Rosch haSchana':      ['רֹאשׁ הַשָּׁנָה',   'Rosch haSchana'],
  'Jom Kippur':          ['יוֹם כִּפּוּר',     'Jom Kippur'],
  'Schawuot':            ['שָׁבוּעוֹת',        'Schawuot'],
  'Tischa beAw':         ['תִּשְׁעָה בְּאָב',  'Tischa beAw'],
  'Simchat Tora':        ['שִׂמְחַת תּוֹרָה',  'Simchat Tora'],
  'Lag baOmer':          ['לַ״ג בָּעֹמֶר',     'Lag baOmer'],
  'Tu biSchwat':         ['טוּ בִּשְׁבָט',     'Tu biSchwat'],

  // Synagoge & Gebet
  'Synagoge':            ['בֵּית כְּנֶסֶת',    'Bejt Kneset'],
  'Rabbi':               ['רַבִּי',            'Rabbi'],
  'Kantor':              ['חַזָּן',             'Chazan'],
  'Torah':               ['תּוֹרָה',           'Tora'],
  'Talmud':              ['תַּלְמוּד',          'Talmud'],
  'Siddur':              ['סִדּוּר',            'Siddur'],
  'Machsor':             ['מַחְזוֹר',           'Machsor'],
  'Minjan':              ['מִנְיָן',            'Minjan'],
  'Kiddusch':            ['קִידּוּשׁ',          'Kiddusch'],
  'Hawdala':             ['הַבְדָּלָה',         'Hawdala'],
  'Birkat haMazon':      ['בִּרְכַּת הַמָּזוֹן','Birkat haMazon'],
  'Schacharit':          ['שַׁחֲרִית',          'Schacharit'],
  'Mincha':              ['מִנְחָה',            'Mincha'],
  'Maariv':              ['מַעֲרִיב',           'Maariv'],

  // Feste & Bräuche
  'Seder':               ['סֵדֶר',             'Seder'],
  'Haggada':             ['הַגָּדָה',           'Haggada'],
  'Matzot':              ['מַצּוֹת',            'Mazot'],
  'Matze':               ['מַצָּה',             'Maza'],
  'Afikoman':            ['אֲפִיקוֹמָן',        'Afikoman'],
  'Menora':              ['מְנוֹרָה',           'Menora'],
  'Chanukkia':           ['חֲנֻכִּיָּה',        'Chanukia'],
  'Dreidel':             ['דְּרֵיידֶל',         'Dreidel'],
  'Grogger':             ['גְּרָגֶּר',           'Groger'],
  'Lulav':               ['לוּלָב',             'Lulaw'],
  'Etrog':               ['אֶתְרוֹג',           'Etrog'],
  'Schofar':             ['שׁוֹפָר',            'Schofar'],
  'Sukka':               ['סֻכָּה',             'Sukka'],
  'Mischloach Manot':    ['מִשְׁלוֹחַ מָנוֹת',  'Mischloach Manot'],
  'Purimspiel':          ['פּוּרִים שְׁפִּיל',  'Purim Schpil'],

  // Gegenstände
  'Kipa':                ['כִּיפָּה',           'Kipa'],
  'Tallit':              ['טַלִּית',            'Tallit'],
  'Tfilin':              ['תְּפִלִּין',          'Tefillin'],
  'Mezuza':              ['מְזוּזָה',           'Mesusa'],
  'Torarolle':           ['סֵפֶר תּוֹרָה',      'Sefer Tora'],
  'Chuppa':              ['חֻפָּה',             'Chuppa'],
  'Ketuba':              ['כְּתוּבָּה',          'Ketuba'],
  'Kidduschbecher':      ['כּוֹס קִידּוּשׁ',    'Kos Kiddusch'],
  'Davidstern':          ['מָגֵן דָּוִד',        'Magen David'],
  'Hamsa':               ['חַמְסָה',            'Chamsa'],

  // Essen
  'Challah':             ['חַלָּה',             'Challa'],
  'Gefilte Fisch':       ['גְּפִילְטֶע פִּיש',  'Gefilte Fisch'],
  'Latke':               ['לַאטְקֶע',           'Latke'],
  'Sufganija':           ['סֻפְגָּנִיָּה',       'Sufganija'],
  'Hamantasche':         ['הַמַנְטַאש',          'Hamantasch'],
  'Tzimmes':             ['צִימֶּס',             'Zimmes'],
  'Bagel':               ['בֵּיגֶל',             'Beigel'],
  'Hummus':              ['חוּמוּס',             'Humus'],
  'Falafel':             ['פָּלָאפֶל',           'Falafel'],
  'Tahini':              ['טְחִינָה',            'Techina'],
  'Schawarma':           ['שָׁווָארְמָה',        'Schawarma'],
  'Haloumi':             ['חָלוּמִי',            'Chalumi'],

  // Grüße & Begriffe
  'Shalom':              ['שָׁלוֹם',            'Schalom'],
  'Schalom':             ['שָׁלוֹם',            'Schalom'],
  'Masel tov':           ['מַזָּל טוֹב',         'Masal tow'],
  'Lehajim':             ['לְחַיִּים',           'Lechajim'],
  'Amen':                ['אָמֵן',              'Amen'],
  'Halleluja':           ['הַלְלוּיָהּ',         'Halleluja'],
  'Baruch':              ['בָּרוּךְ',            'Baruch'],
  'Todah':               ['תּוֹדָה',            'Toda'],
  'Schana towa':         ['שָׁנָה טוֹבָה',       'Schana towa'],
  'Gmar chatima towa':   ['גְּמַר חֲתִימָה טוֹבָה','Gmar chatima towa'],
  'Chag sameach':        ['חַג שָׂמֵחַ',         'Chag sameach'],

  // Orte & Geschichte
  'Jerusalem':           ['יְרוּשָׁלַיִם',       'Jeruschalajim'],
  'Tel Aviv':            ['תֵּל אָבִיב',         'Tel Awiv'],
  'Haifa':               ['חֵיפָה',             'Chejfa'],
  'Tiberias':            ['טְבֶרְיָה',           'Twerja'],
  'Nazareth':            ['נָצְרַת',             'Nazrat'],
  'Jericho':             ['יְרִיחוֹ',           'Jericho'],
  'Masada':              ['מְצָדָה',            'Mezada'],
  'Knesset':             ['כְּנֶסֶת',           'Kneset'],
  'Kibbutz':             ['קִיבּוּץ',           'Kibuz'],
  'Moshav':              ['מוֹשָׁב',            'Moschaw'],
  'Negev':               ['נֶגֶב',             'Negew'],
  'Galiäa':              ['גָּלִיל',            'Galil'],
  'Galiläa':             ['גָּלִיל',            'Galil'],
  'Totes Meer':          ['יָם הַמֶּלַח',        'Jam haMelach'],
  'Jordan':              ['יַרְדֵּן',            'Jarden'],

  // Religion & Allgemein
  'Messias':             ['מָשִׁיחַ',           'Maschiach'],
  'Cherub':              ['כְּרוּב',            'Keruv'],
  'Eden':                ['עֵדֶן',             'Eden'],
  'Golem':               ['גּוֹלֶם',            'Golem'],
  'Dybbuk':              ['דִּיבּוּק',           'Dibbuk'],
  'Kabbalah':            ['קַבָּלָה',           'Kabbala'],
  'Jeschibah':           ['יְשִׁיבָה',          'Jeschiva'],
  'Sanhedrin':           ['סַנְהֶדְרִין',        'Sanhedrin'],
  'Psalm':               ['מִזְמוֹר',           'Mismor'],
  'Exodus':              ['שְׁמוֹת',            'Schmot'],
  'Genesis':             ['בְּרֵאשִׁית',        'Bereschit'],
  'Levitikus':           ['וַיִּקְרָא',          'Wajikra'],
  'Numeri':              ['בְּמִדְבַּר',         'Bemidbar'],
  'Deuteronomium':       ['דְּבָרִים',           'Dwarim'],
};
