// woerter_griechisch.js – Griechisches Wörterbuch für den Schrift-Trainer
// Werte: null = algorithmische Transkription korrekt
//        'ΣchriftForm'  = nur Wörterbuch-Form (Algo für Romanisierung genutzt)
//        ['ΣchriftForm','Romanisierung'] = beides manuell
var WOERTER_GRIECHISCH = {

  // Mathematik & Wissenschaft
  'Pythagoras':          null,
  'Thales':              ['Θαλής',      'Thalis'],
  'Kathete':             ['Κάθετη',     'Katheti'],
  'Hypotenuse':          ['Υποτείνουσα','Ipoteinousa'],
  'Geometrie':           ['Γεωμετρία',  'Geometria'],
  'Mathematik':          ['Μαθηματική', 'Mathimatiki'],
  'Arithmetik':          ['Αριθμητική', 'Arithmitiki'],
  'Symmetrie':           ['Συμμετρία',  'Symmetria'],
  'Parabel':             ['Παραβολή',   'Paravoli'],
  'Hyperbel':            ['Υπερβολή',   'Ipervoli'],
  'Prisma':              ['Πρίσμα',     'Prisma'],
  'Zylinder':            ['Κύλινδρος',  'Kilindros'],
  'Polygon':             ['Πολύγωνο',   'Poligono'],
  'Physik':              ['Φυσική',     'Fysiki'],
  'Biologie':            ['Βιολογία',   'Viologia'],
  'Geographie':          ['Γεωγραφία',  'Geographia'],
  'Astronomie':          ['Αστρονομία', 'Astronomia'],
  'Logik':               ['Λογική',     'Logiki'],
  'Analyse':             ['Ανάλυση',    'Analisi'],
  'Synthese':            ['Σύνθεση',    'Sinthesi'],
  'Hypothese':           ['Υπόθεση',    'Ipothesi'],
  'Atom':                ['Άτομο',      'Atomo'],
  'Elektron':            ['Ηλεκτρόνιο','Ilektronjo'],

  // Kultur & Orte
  'Bibliothek':          ['Βιβλιοθήκη', 'Vivliothiki'],
  'Stadion':             ['Στάδιο',     'Stadio'],
  'Theater':             ['Θέατρο',     'Theatro'],
  'Museum':              ['Μουσείο',    'Mouseio'],
  'Demokratie':          ['Δημοκρατία', 'Dimokratia'],
  'Politik':             ['Πολιτική',   'Politiki'],
  'Philosophie':         ['Φιλοσοφία',  'Filosofia'],
  'Kosmos':              null,
  'Chaos':               null,
  'Chronos':             ['Χρόνος',     'Chronos'],
  'Epoche':              ['Εποχή',      'Epochi'],
  'Mythologie':          ['Μυθολογία',  'Mythologia'],
  'Olymp':               ['Όλυμπος',   'Olimbos'],
  'Akropolis':           ['Ακρόπολη',   'Akropoli'],
  'Sparta':              ['Σπάρτη',     'Sparti'],
  'Athen':               ['Αθήνα',      'Athina'],
  'Europa':              ['Ευρώπη',     'Evropi'],
  'Dialog':              ['Διάλογος',   'Dialogos'],
  'Monolog':             ['Μονόλογος',  'Monologos'],
  'Rhetorik':            ['Ρητορική',   'Ritoriki'],
  'Alphabet':            ['Αλφάβητο',   'Alfavito'],

  // Essen & Reise
  'Feta':                null,
  'Gyros':               null,
  'Ouzo':                null,
  'Tzatziki':            null,
  'Pita':                null,
  'Taverne':             ['Ταβέρνα',    'Taverna'],
  'Olive':               ['Ελιά',       'Elia'],
  'Kreta':               ['Κρήτη',      'Kriti'],
  'Mykonos':             ['Μύκονος',    'Mikonos'],
  'Rhodos':              ['Ρόδος',      'Rodos'],

  // Allgemeine Begriffe
  'Aroma':               ['Άρωμα',      'Aroma'],
  'Basis':               ['Βάση',       'Vasi'],
  'Charisma':            ['Χάρισμα',    'Charisma'],
  'Dosis':               ['Δόση',       'Dosi'],
  'Echo':                ['Ηχώ',        'Icho'],
  'Hymne':               ['Ύμνος',      'Imnos'],
  'Klima':               ['Κλίμα',      'Klima'],
  'Koma':                ['Κώμα',       'Koma'],
  'Melodie':             ['Μελωδία',    'Melodia'],
  'Metrum':              ['Μέτρο',      'Metro'],
  'Optik':               ['Οπτική',     'Optiki'],
  'Orchester':           ['Ορχήστρα',   'Orchisthra'],
  'Pause':               ['Παύση',      'Pavsi'],
  'Phase':               ['Φάση',       'Fasi'],
  'Schema':              ['Σχήμα',      'Schima'],
  'System':              ['Σύστημα',    'Sistima'],
  'Technik':             ['Τεχνική',    'Techniki'],
  'Thema':               ['Θέμα',       'Thema'],
  'Trauma':              ['Τραύμα',     'Travma'],
  'Zentrum':             ['Κέντρο',     'Kentro'],
};
